// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7TGGmZ6HylQ4KOK8cGsqM1TEKjokN1OM',
    appId: '1:127285327218:web:693925a55b974438bb99eb',
    messagingSenderId: '127285327218',
    projectId: 'getxchat-d0426',
    authDomain: 'getxchat-d0426.firebaseapp.com',
    storageBucket: 'getxchat-d0426.appspot.com',
    measurementId: 'G-2W15YYQ0WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFmqMcmL4My7nCbphV3LXg_FBW_zp4KyQ',
    appId: '1:127285327218:android:38d5098b5d286d18bb99eb',
    messagingSenderId: '127285327218',
    projectId: 'getxchat-d0426',
    storageBucket: 'getxchat-d0426.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1NLzD8Qud12rFdnovMzjG75PnbeagMr4',
    appId: '1:127285327218:ios:48e7e654c7288ff9bb99eb',
    messagingSenderId: '127285327218',
    projectId: 'getxchat-d0426',
    storageBucket: 'getxchat-d0426.appspot.com',
    iosBundleId: 'com.example.getChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1NLzD8Qud12rFdnovMzjG75PnbeagMr4',
    appId: '1:127285327218:ios:a3917ebdb61b2016bb99eb',
    messagingSenderId: '127285327218',
    projectId: 'getxchat-d0426',
    storageBucket: 'getxchat-d0426.appspot.com',
    iosBundleId: 'com.example.getChat.RunnerTests',
  );
}
